In [29]:
import numpy as np
import pandas as pd
from pathlib import Path

In [30]:
file_path= Path.cwd()
file_path

WindowsPath('c:/Users/komet/Documents/y5/data visualization')

In [31]:
file_name="season-1920.csv"
data_19_20 = pd.read_csv(file_path / file_name)
file_name="season-2021.csv"
data_20_21 = pd.read_csv(file_path / file_name)
file_name="season-2122.csv"
data_21_22 = pd.read_csv(file_path / file_name)

In [32]:
# Empty array
tables = []

tables = pd.concat([data_19_20, data_20_21, data_21_22])
tables=pd.DataFrame(tables)
tables

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,09/08/19,Liverpool,Norwich,4,1,H,4,0,H,M Oliver,...,7,5,9,9,11,2,0,2,0,0
1,10/08/19,West Ham,Man City,0,5,A,0,1,A,M Dean,...,3,9,6,13,1,1,2,2,0,0
2,10/08/19,Bournemouth,Sheffield United,1,1,D,0,0,D,K Friend,...,3,3,10,19,3,4,2,1,0,0
3,10/08/19,Burnley,Southampton,3,0,H,0,0,D,G Scott,...,4,3,6,12,2,7,0,0,0,0
4,10/08/19,Crystal Palace,Everton,0,0,D,0,0,D,J Moss,...,2,3,16,14,6,2,2,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,22/05/22,Crystal Palace,Man United,1,0,H,1,0,H,M Atkinson,...,3,4,12,22,3,6,2,4,0,0
376,22/05/22,Leicester,Southampton,4,1,H,0,0,D,J Moss,...,6,2,10,5,3,3,0,1,0,0
377,22/05/22,Liverpool,Wolves,3,1,H,1,1,D,A Taylor,...,8,5,6,3,5,3,1,0,0,0
378,22/05/22,Man City,Aston Villa,3,2,H,0,1,A,M Oliver,...,5,2,5,11,13,1,0,1,0,0
379,22/05/22,Norwich,Tottenham,0,5,A,0,2,A,C Kavanagh,...,0,13,13,7,3,2,3,1,0,0

In [33]:
home = pd.DataFrame({
    "team": tables["HomeTeam"],
    "goals": tables["FTHG"],
    "wins": (tables["FTR"] == "H").astype(int),
    "draws": (tables["FTR"] == "D").astype(int),
    "losses": (tables["FTR"] == "A").astype(int),

    "halftime_goals": tables["HTHG"],
    "halftime_wins": (tables["HTR"] == "H").astype(int),
    "halftime_draws": (tables["HTR"] == "D").astype(int),
    "halftime_losses": (tables["HTR"] == "A").astype(int),

    "shots": tables["HS"],
    "shots_on_target": tables["HST"],
    "fouls_commited": tables["HF"],
    "corners": tables["HC"],
    "yellow_cards": tables["HY"],
    "red_cards": tables["HR"]
})

In [34]:
away = pd.DataFrame({
    "team": tables["AwayTeam"],
    "goals": tables["FTAG"],
    "wins": (tables["FTR"] == "A").astype(int),
    "draws": (tables["FTR"] == "D").astype(int),
    "losses": (tables["FTR"] == "H").astype(int),

    "halftime_goals": tables["HTAG"],
    "halftime_wins": (tables["HTR"] == "A").astype(int),
    "halftime_draws": (tables["HTR"] == "D").astype(int),
    "halftime_losses": (tables["HTR"] == "H").astype(int),

    "shots": tables["AS"],
    "shots_on_target": tables["AST"],
    "fouls_commited": tables["AF"],
    "corners": tables["AC"],
    "yellow_cards": tables["AY"],
    "red_cards": tables["AR"]
})

In [35]:
combined = pd.concat([home, away])

In [36]:
combined_data = combined.groupby("team").sum().reset_index()

In [37]:
combined_data

,team,goals,wins,draws,losses,halftime_goals,halftime_wins,halftime_draws,halftime_losses,shots,shots_on_target,fouls_commited,corners,yellow_cards,red_cards
0,Arsenal,172,54,24,36,87,42,40,32,1457,500,1129,648,193,14
1,Aston Villa,148,38,21,55,66,37,43,34,1424,499,1291,611,208,6
2,Bournemouth,40,9,7,22,20,7,13,18,389,121,369,194,73,3
3,Brentford,48,13,7,18,16,7,15,16,442,154,371,159,61,3
4,Brighton,121,30,43,41,50,31,44,39,1438,437,1205,599,172,10
5,Burnley,110,32,32,50,51,23,45,46,1179,389,1190,527,183,2
6,Chelsea,203,60,27,27,93,49,45,20,1775,643,1228,716,171,4
7,Crystal Palace,122,34,33,47,53,31,42,41,1137,398,1249,504,182,5
8,Everton,134,41,24,49,70,31,53,30,1308,448,1226,531,204,11
9,Fulham,27,5,13,20,12,6,18,14,442,136,484,164,66,3
10,Leeds,104,27,16,33,41,18,29,29,1007,353,896,402,161,4
11,Leicester,197,52,24,38,78,30,53,31,1456,544,1190,621,155,4
12,Liverpool,247,80,20,14,116,59,42,13,1928,701,1090,803,128,2
13,Man City,284,82,14,18,136,65,32,17,2064,736,1042,862,148,7
14,Man United,196,55,33,26,85,42,42,30,1572,615,1280,600,211,3
15,Newcastle,128,36,30,48,59,23,56,35,1240,421,1149,472,205,7
16,Norwich,49,10,13,53,25,13,26,37,782,240,719,327,122,5
17,Sheffield United,59,21,14,41,26,15,32,29,679,214,869,383,134,5
18,Southampton,141,36,27,51,74,38,37,39,1405,517,1278,622,168,9
19,Tottenham,198,56,24,34,102,51,36,27,1380,534,1248,563,202,6
20,Watford,70,14,15,47,32,13,28,35,820,247,924,329,132,6
21,West Brom,35,5,11,22,18,6,14,18,340,112,404,145,51,4
22,West Ham,171,45,25,44,83,37,50,27,1318,486,1085,549,157,7
23,Wolves,125,42,29,43,49,22,53,39,1323,435,1196,570,169,4